### ISSUE TITLE
Перейти на использование i18n в acceptance-тестах

### ISSUE THREAD

**Issue by igv-on-dev** [igv-on-dev/stack-over-ror#27]
Подход описан  в https://robots.thoughtbot.com/better-tests-through-internationalization.

Рассмотреть необходимость использования https://github.com/mcasimir/devise-i18n-views

**Comment by palkan** [comment]
Хорошая статья.
Обрати внимание на [Rails Guide](http://guides.rubyonrails.org/i18n.html#organization-of-locale-files), касающийся распределения локализации по файлам. Лучше не хранить все в одном `en.yml`.
